### PR TITLE
config: adding `advisor` & removing some older API Versions

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR:

* Adds `advisor` @ `2020-01-01`
* Removes `azurestackhci` @ `2022-09-01` and `2022-10-01`
* Removes `domainservices` (AAD) @ `2020-01-01`, `2021-03-01`, `2022-09-01` and `2022-12-01`
* Removes `recoveryservicessiterecovery` @ `2022-05-01` and `2022-09-10` (incorporating the changes from #1860)

~Dependent on https://github.com/hashicorp/terraform-provider-azurerm/pull/20318 which updates the Azure Stack HCI API Version to latest~

### CODE REVIEW

**Comment by hc-github-team-tf-azure** [comment]
No new resource IDs found.

**Comment by hc-github-team-tf-azure** [comment]
No new resource IDs found.

**Comment by hc-github-team-tf-azure** [comment]
No new resource IDs found.

**Review by jackofallops — APPROVED** [review]
LGTM 👍

**Pull request merged**
