### PR TITLE
Add containerservice 2024-02-01

### PR DESCRIPTION
**Pull request by timja**
This is a starting point for:
https://github.com/hashicorp/terraform-provider-azurerm/issues/23982

API I'm after:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2024-02-01/managedClusters.json#L7330-L7333

I'm a bit confused on how services work when there's multiple under them.
e.g. the `2023-10-15` is for fleet manager and not AKS but nothing seems to distinguish the multiple services

### CODE REVIEW

**Comment by stephybun** [comment]
Thanks for this PR @timja. Unfortunately I've had to apply the blocked label to this since MSFT is in discussion with us about removing support for preview features in the azurerm AKS resource. Please see [this comment and discussion thread](https://github.com/hashicorp/pandora/pull/3469#issuecomment-1849556744) for more details.

Once we have an update we can let you know if we can proceed with this PR. Thanks!

**Comment by tombuildsstuff** [comment]
Superseded by https://github.com/hashicorp/pandora/pull/3939?

**Comment by timja** [comment]
> Superseded by #3939?

It's not, 2024-01-02-preview would be a new version with the specific feature I'm after here.

The conversation continued for a bit here https://github.com/hashicorp/pandora/pull/3469#issuecomment-1881670326 but doesn't seem to be concluded.

A workaround in the meantime is to use az api by the looks of it.

**Comment by gravufo** [comment]
The feature in question (cost analysis) is apparently GA now, so this PR could be updated to use the newest API and get merged?
See [here](https://azure.microsoft.com/en-us/updates/generally-available-cost-analysis-addon-for-aks/#:~:text=Cost%20analysis%20add%2Don%20for%20AKS%20is%20now%20Generally%20Available,addition%20to%20Azure%20asset%20categories.)

**Comment by timja** [comment]
> The feature in question (cost analysis) is apparently GA now, so this PR could be updated to use the newest API and get merged? See [here](https://azure.microsoft.com/en-us/updates/generally-available-cost-analysis-addon-for-aks/#:~:text=Cost%20analysis%20add%2Don%20for%20AKS%20is%20now%20Generally%20Available,addition%20to%20Azure%20asset%20categories.)

I saw that but there isn't a new API for it available that I can see, at least not on the website:
https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/2024-01-02-preview/managedclusters?pivots=deployment-language-arm-template

**Comment by FuNK3Y** [comment]
Is https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/2024-01-02-preview/managedclusters?pivots=deployment-language-arm-template#managedclustercostanalysis-1 not the API you are looking for ?

**Comment by timja** [comment]
Yes but it’s preview and there’s concerns around that from the AKS team, Tom has linked to the new API that should hopefully address it

**Comment by timja** [comment]
should be unblocked now

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Pull request merged**
