### PR TITLE
`DevCenter` @ `2022-04-01`

### PR DESCRIPTION
**Pull request by jiaweitao001**
Onboarding Azure DevCenter. 

Swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/devcenter/resource-manager/Microsoft.DevCenter/stable/2023-04-01

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
x-link: https://github.com/hashicorp/go-azure-sdk/issues/549

**Comment by tombuildsstuff** [comment]
Looks like there's a Swagger issue blocking this one:

```
2023-06-21T08:45:22.664Z [INFO]  Importer for Service "DevCenter".Importer for API Version "2023-04-01": ❌ Service "DevCenter" - Api Version "2023-04-01"
Error: -21T08:45:22.664Z [ERROR] Importer for Service "DevCenter".Importer for API Version "2023-04-01":      💥 Error: parsing Swagger files: parsing files in "../../swagger/specification/devcenter/resource-manager/Microsoft.DevCenter/stable/2023-04-01": parsing definition: finding resources for tag "Environment Types": finding nested items yet to be parsed: appending model: appending models: different model objects. First fields: map[roles:{Required:false ReadOnly:false Sensitive:false JsonName:roles Description:A map of roles to assign to the environment creator. CustomFieldType:<nil> ObjectDefinition:0xc0001c4fc0}]. Second fields: map[creatorRoleAssignment:{Required:false ReadOnly:false Sensitive:false JsonName:creatorRoleAssignment Description:The role definition assigned to the environment creator on backing resources. CustomFieldType:<nil> ObjectDefinition:0xc0001c5d40} deploymentTargetId:{Required:false ReadOnly:false Sensitive:false JsonName:deploymentTargetId Description:Id of a subscription that the environment type will be mapped to. The environment's resources will be deployed into this subscription. CustomFieldType:<nil> ObjectDefinition:0xc0001c5b80} status:{Required:false ReadOnly:false Sensitive:false JsonName:status Description:Defines whether this Environment Type can be used in this Project. CustomFieldType:<nil> ObjectDefinition:0xc0001c5c00} userRoleAssignments:{Required:false ReadOnly:false Sensitive:false JsonName:userRoleAssignments Description:Role Assignments created on environment backing resources. This is a mapping from a user object ID to an object of role definition IDs. CustomFieldType:<nil> ObjectDefinition:0xc0001c5f00}]
2023/06/21 08:45:22 Error: parsing data for Service "DevCenter": parsing data for Service "DevCenter" / Version "2023-04-01": parsing Swagger files: parsing files in "../../swagger/specification/devcenter/resource-manager/Microsoft.DevCenter/stable/2023-04-01": parsing definition: finding resources for tag "Environment Types": finding nested items yet to be parsed: appending model: appending models: different model objects. First fields: map[roles:{Required:false ReadOnly:false Sensitive:false JsonName:roles Description:A map of roles to assign to the environment creator. CustomFieldType:<nil> ObjectDefinition:0xc0001c4fc0}]. Second fields: map[creatorRoleAssignment:{Required:false ReadOnly:false Sensitive:false JsonName:creatorRoleAssignment Description:The role definition assigned to the environment creator on backing resources. CustomFieldType:<nil> ObjectDefinition:0xc0001c5d40} deploymentTargetId:{Required:false ReadOnly:false Sensitive:false JsonName:deploymentTargetId Description:Id of a subscription that the environment type will be mapped to. The environment's resources will be deployed into this subscription. CustomFieldType:<nil> ObjectDefinition:0xc0001c5b80} status:{Required:false ReadOnly:false Sensitive:false JsonName:status Description:Defines whether this Environment Type can be used in this Project. CustomFieldType:<nil> ObjectDefinition:0xc0001c5c00} userRoleAssignments:{Required:false ReadOnly:false Sensitive:false JsonName:userRoleAssignments Description:Role Assignments created on environment backing resources. This is a mapping from a user object ID to an object of role definition IDs. CustomFieldType:<nil> ObjectDefinition:0xc0001c5f00}]
```

**Comment by am-lim** [comment]
@tombuildsstuff I am from the team owning the swagger. Do you have any suggestions on how to fix this issue? Thank you.

**Comment by tombuildsstuff** [comment]
@am-lim looking into this one, it appears the root of the issue is that the `EnvironmentType` model is duplicated, once using the in-lined approach (in `creatorRoleAssignment`) and another by reference (`UserRoleAssignment`), which is unexpected/should be able to be parsed.

The following diff fixes this issue:

```diff
diff --git a/specification/devcenter/resource-manager/Microsoft.DevCenter/stable/2023-04-01/devcenter.json b/specification/devcenter/resource-manager/Microsoft.DevCenter/stable/2023-04-01/devcenter.json
index e0b943d07a..424114f64d 100644
--- a/specification/devcenter/resource-manager/Microsoft.DevCenter/stable/2023-04-01/devcenter.json
+++ b/specification/devcenter/resource-manager/Microsoft.DevCenter/stable/2023-04-01/devcenter.json
@@ -3406,15 +3406,11 @@
         "creatorRoleAssignment": {
           "description": "The role definition assigned to the environment creator on backing resources.",
           "type": "object",
-          "properties": {
-            "roles": {
-              "type": "object",
-              "description": "A map of roles to assign to the environment creator.",
-              "additionalProperties": {
-                "$ref": "#/definitions/EnvironmentRole"
-              }
+          "allOf": [
+            {
+              "$ref": "#/definitions/RoleAssignment"
             }
-          }
+          ]
         },
         "userRoleAssignments": {
           "description": "Role Assignments created on environment backing resources. This is a mapping from a user object ID to an object of role definition IDs.",
@@ -3674,10 +3670,8 @@
         }
       }
     },
-    "UserRoleAssignment": {
+    "RoleAssignment": {
       "type": "object",
-      "description": "Mapping of user object ID to role assignments.",
-      "x-ms-client-name": "userRoleAssignmentValue",
       "properties": {
         "roles": {
           "type": "object",
@@ -3688,6 +3682,16 @@
         }
       }
     },
+    "UserRoleAssignment": {
+      "type": "object",
+      "description": "Mapping of user object ID to role assignments.",
+      "x-ms-client-name": "userRoleAssignmentValue",
+      "allOf": [
+        {
+          "$ref": "#/definitions/RoleAssignment"
+        }
+      ]
+    },
     "OperationStatus": {
       "description": "The current status of an async operation",
       "type": "object",
```

However the import should be able to process this as it is, so I believe this is ultimately a bug in the importer which needs fixing.

**Comment by am-lim** [comment]
Thanks for the suggestion @tombuildsstuff. Is it possible that the bug in the importer will be fixed soon?

**Comment by am-lim** [comment]
@tombuildsstuff The suggestion would cause a breaking change on our side which would involve difficulty in getting our SDK updated in the immediate future. Could we prioritize the importer bug to be fixed?

**Comment by am-lim** [comment]
@tombuildsstuff Thanks for fixing the bug! Any update on this PR? Can the checks be re-run?

**Comment by tombuildsstuff** [comment]
@am-lim FWIW the bug isn't fixed from our side, I've added a test for this in the branch above whilst I have the context, but as there's some higher priority items from our side, so unfortunately I don't have a timeframe for when this'll be fixed in the importer.

That said, if @jiaweitao001 or someone else is able to send a PR to fix that in the interim then we'd be happy to accept a PR for that - but in the short-term the most reliable way to fix this is going to be to update the Swagger (which, fwiw, I don't believe this'd be a breaking change, since the SDK output is the same?)

**Comment by tombuildsstuff** [comment]
@jiaweitao001 @wuxu92 mind rebasing this one so we can get this in?

**Comment by jiaweitao001** [comment]
@tombuildsstuff Thanks for reminding. Rebased.

**Comment by am-lim** [comment]
@tombuildsstuff Any update on whether this PR can be checked in?

**Review by tombuildsstuff — APPROVED** [review]

**Comment by tombuildsstuff** [comment]
@am-lim @jiaweitao001 looks like there's an issue with the Swagger here where this field isn't marked as readonly: https://github.com/Azure/azure-rest-api-specs/pull/26189 - mind taking a look so we can add support for this?

**Comment by am-lim** [comment]
@tombuildsstuff the change looks good, verified by @nickdepinet

**Comment by am-lim** [comment]
@tombuildsstuff Can you confirm if the PR https://github.com/Azure/azure-rest-api-specs/pull/26189 is required for a release on your side? There is a long backlog on ARM reviews and would prefer if Terraform development can start for Azure DevCenter

**Comment by tombuildsstuff** [comment]
Awesome, thanks @am-lim :)

**Pull request merged**
