### PR TITLE
Add 2022-09-01 as a supported version for Search

### PR DESCRIPTION
**Pull request by mattmsft**

### CODE REVIEW

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this @mattmsft

**Comment by tombuildsstuff** [comment]
hey @mattmsft 

Thanks for this PR - whilst this PR looks good in order to merge this we'll need the CLA to be signed, would you mind signing that so that we can get this merged which'll generate the new API version into `hashicorp/go-azure-sdk`? FWIW the build failure here is unrelated, and will be fixed by #2237 - apologies for that.

Thanks!

**Comment by tombuildsstuff** [comment]
hey @mattmsft 

I hope you don't mind but since we've not heard back from you here I'm going to close this PR in favour of #2307 which adds support for this API version - which'll allow us add support for this API Version into `hashicorp/go-azure-sdk`.

Thanks!

**Comment by mattmsft** [comment]
Not a problem at all

**Pull request closed without merging**
