### PR TITLE
Update resource-manager.hcl for nginx new version

### PR DESCRIPTION
**Pull request by zaowang-ms**
This is the PR updating available versions of nginx on Azure.

### CODE REVIEW

**Comment by puneetsarna** [comment]
Thanks for doing this @zaowang-ms . This looks good to me. Here's the link to the swagger spec 2024-06-01-preview:

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/nginx/resource-manager/NGINX.NGINXPLUS/preview/2024-06-01-preview/swagger.json

**Comment by puneetsarna** [comment]
@catriona-m Thank you for starting to review this PR. This changeset looks very similar to https://github.com/hashicorp/pandora/pull/3830/files from @tombuildsstuff . I can't think of why the unit test would fail to import the swagger spec. Can you please share some pointers on how to start debugging this?

**Comment by puneetsarna** [comment]
@zaowang-ms I think I see the problem. Can you please update your feature branch on your own fork to latest main of this repository? It appears to be the case that your fork has out of date sub modules and you should sync it with the upstream (this repository) to get the unit tests to pass.

**Comment by puneetsarna** [comment]
@catriona-m I see @zaowang-ms updated the fork and it now has the latest swagger submoduled. Can you please trigger the workflows again. I think they will pass now.

**Review by catriona-m — APPROVED** [review]
Thanks @zaowang-ms & @puneetsarna - the tests are passing now and this LGTM 👍

**Pull request merged**
