### PR TITLE
Importer: TF example add up the provider block and the dependencies if any

### PR DESCRIPTION
**Pull request by magodo**
Make the swagger import generated terraform examples to add up the provider block and the dependencies if any.

### CODE REVIEW

**Comment by hc-github-team-tf-azure** [comment]
No new resource IDs found.

**Comment by hc-github-team-tf-azure** [comment]
No new resource IDs found.

**Comment by tombuildsstuff** [comment]
hey @magodo 

Thanks for this PR - apologies for the delayed review of this one.

We've actually ended up entirely reworking how tests are generated in https://github.com/hashicorp/pandora/pull/2583, which includes dynamically building up both the dependencies and the provider block (so that the provider block is now output per-test rather than in the template) - meaning that this PR has been superseded in a slightly different manner.

As such whilst I'd like to thank you for this contribution, since this has ended up being reimplemented in a slightly different manner I'm going to close this PR for the moment - however you can see the end result of this in [this upstream PR on the `hashicorp/terraform-provider-azurerm` repository](https://github.com/hashicorp/terraform-provider-azurerm/pull/22045).

Thanks!

**Comment by magodo** [comment]
@tombuildsstuff Thank you for the update! One remaining question about the end result is that, e.g. the role assigned identiy example being generated seems not contain the resource group template, is that as expected?

**Comment by tombuildsstuff** [comment]
@magodo ah good spot, that's not intentional / we should be outputting that 😅 - will sort that now

**Comment by tombuildsstuff** [comment]
https://github.com/hashicorp/pandora/pull/2624

**Pull request closed without merging**
