### PR TITLE
tools/importer-rest-api-specs: adding a swagger data workaround for https://github.com/Azure/azure-rest-api-specs/pull/21581

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR adds a temporary Swagger workaround for https://github.com/Azure/azure-rest-api-specs/pull/21581 - moving the `Update` operation into the `StreamingEndpoints` package, so that the models can be reused

Unblocks https://github.com/hashicorp/terraform-provider-azurerm/pull/19285

### CODE REVIEW

**Comment by hc-github-team-tf-azure** [comment]
No new resource IDs found.

**Comment by hc-github-team-tf-azure** [comment]
No new resource IDs found.

**Comment by hc-github-team-tf-azure** [comment]
No new resource IDs found.

**Review by jackofallops — APPROVED** [review]
LGTM 👍

**Pull request merged**
