### PR TITLE
Add postgresql 2023-06-01-preview API

### PR DESCRIPTION
**Pull request by timja**
Needed for postgres 16: https://github.com/Azure/azure-rest-api-specs/blob/a4b7802e963b3a77b885d8c7c1616cd1870877fb/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/y/FlexibleServers.json#L394

### CODE REVIEW

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Comment by timja** [comment]
🚢 ? 😄

**Comment by tombuildsstuff** [comment]
@timja in a queue (#3358 needs to go first) - but shortly :)

**Comment by timja** [comment]
Did I miss something? It hasn't seemed to have generated the API in https://github.com/hashicorp/pandora/tree/main/api-definitions/resource-manager/PostgreSql

**Comment by tombuildsstuff** [comment]
@timja there's a data fix needed - #3361 - once that's merged the API Definitions will be regenerated (example #3360) and then once that's merged `hashicorp/go-azure-sdk` gets regenerated - should be there in a bit

**Comment by tombuildsstuff** [comment]
@timja FYI https://github.com/hashicorp/go-azure-sdk/pull/741 - once the PR's merged `hashicorp/go-azure-sdk` will release itself, then update `hashicorp/terraform-provider-azurerm` and (_try_ to) update the `postgres` package fwiw

**Comment by tombuildsstuff** [comment]
Ah alas looks like there might be a breaking change in the new psql version, but the SDK is being upgraded in this PR: https://github.com/hashicorp/terraform-provider-azurerm/pull/23922/commits/7fcfd18f560e6e6ff6f6f814e4820d2809988ca1

**Comment by timja** [comment]
> Ah alas looks like there might be a breaking change in the new psql version, but the SDK is being upgraded in this PR: [hashicorp/terraform-provider-azurerm@7fcfd18](https://github.com/hashicorp/terraform-provider-azurerm/commit/7fcfd18f560e6e6ff6f6f814e4820d2809988ca1)

weird, I didn't hit any issues when I upgraded it:
https://github.com/hashicorp/terraform-provider-azurerm/pull/24016

**Pull request merged**
