### PR TITLE
config: add `deviceupdate` @ `2022-10-01`

### PR DESCRIPTION
**Pull request by myc2h6o**
This is a new resource requested by service team. The GA date is 9/30.
[Swagger](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/deviceupdate/resource-manager/Microsoft.DeviceUpdate/stable/2022-10-01)
[Document](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/create-device-update-account)

### CODE REVIEW

**Comment by myc2h6o** [comment]
@tombuildsstuff is this change good to go?

**Comment by katbyte** [comment]
@myc2h6o  - as this was forked and opened before the repo went public and the GHA's functioned correctly - you'll need to re-fork the repo and open a new PR with this change for them to property trigger. Thanks!

**Review by katbyte — CHANGES_REQUESTED** [review]
see above comment

**Comment by myc2h6o** [comment]
Closing the pr in favor of #1699

**Pull request closed without merging**
