### PR TITLE
Config: add Workloads@2024-09-01

### PR DESCRIPTION
**Pull request by neil-yechenwei**
Service team is requesting new feature "ManagedResourcesNetworkAccessType". As this property only exists in the latest stable API version 2024-09-01, so we have to involve it.

### CODE REVIEW

**Comment by stephybun** [comment]
@neil-yechenwei can you please resolve the conflict? I'll merge this once done.

**Comment by neil-yechenwei** [comment]
@stephybun , thanks. I resolved the conflict.

**Review by stephybun — APPROVED** [review]
Thanks @neil-yechenwei LGTM 👍

**Comment by neil-yechenwei** [comment]
@stephybun , could you generate a new version for https://github.com/hashicorp/go-azure-sdk and sync to https://github.com/hashicorp/terraform-provider-azurerm for Workloads@2024-09-01? Thanks.

**Pull request merged**
